[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    --verbose
    --cov=.
    --cov-report=term-missing
    --cov-report=html:tests/coverage_report
    -p no:warnings

markers =
    unit: Small, isolated tests
    integration: Tests that interact with external systems or multiple modules
    slow: Tests that take a long time to run
